-- 입양을 간 기록(ANIMAL_OUTS DATETIME 2013-12-22 11:30:00)은 있는데
-- 보호소에 들어온 기록(ANIMAL_INS DATETIME 2018-01-22 14:32:00)이 없는
-- 동물의 ID(ANIMAL_ID)와 이름(NAME)을
-- ID 순으로 조회
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I RIGHT OUTER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID