-- 분기별 대장균의 개체 총 수
-- 각 분기에는 Q를 붙이고, 오름차순 정렬
-- QUARTER, COUNT(GENOTYPE) AS ECOLI_COUNT
SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE), "Q") AS QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER