-- MEMBER_ID 기준으로 JOIN
-- 리뷰를 가장 많이 작성한 회원의 리뷰(MAX R REVIEW_ID)
-- 회원 이름(M MEMBER_NAME), 리뷰 텍스트(R REVIEW_TEXT), 리뷰 작성일 (R REVIEW_DATE)
-- 리뷰 작성일(R REVIEW_DATE)을 기준으로 오름차순, 리뷰 텍스트(R REVIEW_TEXT)를 기준으로 오름차순
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT

