-- 보호 시작일(ANIMAL_INS DATETIME) 보다 입양일(ANIMAL_OUTS DATETIME)이 더 빠른
-- 동물의 아이디(ANIMAL_INS ANIMAL_ID)와 이름(ANIMAL_INS NAME)
-- JOIN 기준: ANIMAL_ID
-- 보호 시작일이 빠른 순으로
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME