-- 자동차 종류가 '세단'(CAR_RENTAL_COMPANY_CAR CAR_TYPE = '세단')인 자동차들 중
-- 10월에 대여를 시작한 기록(CAR_RENTAL_COMPANY_RENTAL_HISTORY START_DATE = '10월')이 있는
-- 자동차 ID 리스트: CAR_ID를 기준으로 join
-- 자동차 ID 리스트는 중복이 없어야 하며(SELECT DISTINCT), 자동차 ID를 기준으로 내림차순 정렬
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
     ON C.CAR_ID = H.CAR_ID
WHERE TO_CHAR(H.START_DATE, 'YYYY-MM') = '2022-10'
      AND C.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC