-- 2022년 1월 도서 판매량 합산
-- CATEGORY, TOTAL_SALES -> SUM
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY